version: 2.1.0-dev.{build}
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
image: Visual Studio 2019

configuration: Release

init:
- ps: |
    git config --global core.autocrlf true
    Write-Host "Appveyor build version: $env:APPVEYOR_BUILD_VERSION"
    $env:GIT_HASH=$env:APPVEYOR_REPO_COMMIT.Substring(0, 10)
    Write-Host "Git commit hash: $env:GIT_HASH"
    $version_parts = $env:APPVEYOR_BUILD_VERSION -split '-'
    $version = $version_parts[0]
    $pr_part = ""
    If ($version_parts.Length -ge 3) { $pr_part=".$($version_parts[2])" }
    $version = "$($version)-pre.$($env:APPVEYOR_BUILD_NUMBER)$pr_part"
    Write-Host "Computed version: $version"
    If ($env:APPVEYOR_REPO_TAG -and ($env:APPVEYOR_REPO_TAG_NAME -match "^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$"))
    {
        $version=$env:APPVEYOR_REPO_TAG_NAME.Substring(1)
        Write-Host "Tagged version: $version"
    }
    Update-AppveyorBuild -Version "$version"

dotnet_csproj:
  patch: true
  file: '**\Semver.csproj'
  package_version: '{version}'
  informational_version: "{version}+$(GIT_HASH)"

before_build:
  - dotnet restore
  
build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true

# Test Discovery was running both xUnit and dotnet test.
# To prevent that, use a test script to run dotnet test.
test_script:
  - dotnet test "Semver.Test"
